name: CI

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main, next ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: feathers
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
      
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Fix better-sqlite3 native bindings
        run: |
          # Rebuild native dependencies
          pnpm rebuild better-sqlite3
          
          # Find where the binding file was actually built
          echo "Looking for better_sqlite3.node files..."
          find . -name "better_sqlite3.node" -type f 2>/dev/null || true
          
          # Copy binding to expected locations
          # First, try to find the built file
          BINDING=$(find . -name "better_sqlite3.node" -type f 2>/dev/null | head -1)
          
          if [ -n "$BINDING" ]; then
            echo "Found binding at: $BINDING"
            
            # Create expected directories and copy the binding
            mkdir -p node_modules/better-sqlite3/lib/binding/node-v115-linux-x64
            cp "$BINDING" node_modules/better-sqlite3/lib/binding/node-v115-linux-x64/better_sqlite3.node
            
            # Also copy to other possible locations
            mkdir -p node_modules/better-sqlite3/build/Release
            cp "$BINDING" node_modules/better-sqlite3/build/Release/better_sqlite3.node
            
            echo "Copied binding to expected locations"
          else
            echo "Warning: Could not find better_sqlite3.node file"
          fi
      
      - name: Build packages
        run: pnpm run compile
      
      - name: Run linter
        run: pnpm run lint
      
      - name: Run tests
        run: pnpm test
        env:
          CI: true
          TEST_DB: postgres
          NODE_OPTIONS: --experimental-vm-modules
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false
          verbose: true
